import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext } from 'react';
import styled, { ThemeContext } from 'styled-components';

const Text: NextPage = () => {
	return (
		<Wrapper>
			<Head>
				<title>Kyle McKell</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header>
				<NiftyText>Heya</NiftyText>, I&apos;m Kyle
			</Header>
		</Wrapper>
	);
};

const Wrapper = styled.div`
	background-color: ${(props) => props.theme.colors.backgroundColor};
	width: 100%;
	height: 100%;
	min-height: 100vh;
`;

const Header = styled.h1``;

const NiftyText = styled.span`
	font-family: var(--font-family-nifty);
	font-weight: var(--font-weight-medium);
`;

export default Text;
